Доработка функционала по ТЗ 6 + изменения по стилю от GIT
CMEL123/java-kanban pull request #3
Opened 2024-09-07 14:42 UTC by CMEL123

Из-за того что я случайно сделал слияние с главной веткой, пришлось откатить и заново закоммитить

2024-09-09 10:31 UTC, vlolad requested changes
Привет!

Всё в целом хорошо, буквально две мелкие правки и будет вообще отлично. В менеджере историй есть одно задвоение операции, а в тестах кое-где дублирование кода жуткое, надо упростить)

Хорошего дня!

2024-09-09 10:31 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +    private static class Node {
Лучше вложенные классы располагать после всего кода основного класса. Это не описано в код-конвенции вроде, но чаще всего именно так располагают
Некритично, просто пожелание)

2024-09-09 10:31 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +        history.remove(id);
Метод removeNode внутри уже удаляет из списка истории ноду, это лишняя операция

2024-09-09 10:31 UTC, vlolad commented on test/service/InMemoryHistoryManagerTest.java
> +        Task t10 = new Task("Задача10", "Задача2d", 12345, Status.IN_PROGRESS);
это всё можно обернуть в блок for, где сразу создается новая задача и добавляется в менеджер. переменная итерирования i удобно добавляется в строку названия/описания

2024-09-09 18:22 UTC, CMEL123 commented on src/service/InMemoryHistoryManager.java
> +    private static class Node {
Буду знать

2024-09-09 18:22 UTC, CMEL123 commented on src/service/InMemoryHistoryManager.java
> +        history.remove(id);
Убрал

2024-09-09 18:23 UTC, CMEL123 commented on test/service/InMemoryHistoryManagerTest.java
> +        Task t10 = new Task("Задача10", "Задача2d", 12345, Status.IN_PROGRESS);
Оптимизировал

2024-09-11 09:58 UTC, vlolad approved these changes
Привет!

Всё поправлено, принято с:

2024-09-11 09:58 UTC, vlolad commented on test/service/InMemoryHistoryManagerTest.java
> +        for (int i = 1; i < 12; i++) {
Насколько сразу строк меньше стало)

2024-09-21 05:27 UTC, merged