ТЗ 9
CMEL123/java-kanban pull request #6
Opened 2024-10-21 10:56 UTC by CMEL123

2024-10-22 12:35 UTC, vlolad requested changes
Привет!

Основное замечание - надо декомпозировать хендлеры, в таком виде не подходит. Подробнее комментарии оставил
Также по мелочи есть замечания и пожелания. Один момент - я не успел проверить сам, но вроде как Gson умеет парсить обычные Enum-атрибуты, просто в метод парсинга передавай не TypeToken, а требуемый для конвертации класс. Уверен на 90%, что заработает как надо)

Хорошего дня!

2024-10-22 12:35 UTC, vlolad commented on src/converter/DurationTypeAdapter.java
> +        jsonWriter.value(duration.toString());
Если в качестве продолжительности используешь минуты, то лучше парсить числами, а не строкой. В методе write тогда будет изменение на `duration.toMinutes()`, а в read - `return Duration.ofMinutes(jsonReader.nextInt());`

Комментарий на улучшение, по желанию

2024-10-22 12:35 UTC, vlolad commented on src/converter/JsonTaskParser.java
> +            .registerTypeAdapter(LocalDateTime.class, new StatusTypeAdapter())
Ошибка в классе, вызывается совсем другой адаптер
Может он и не нужен?:

2024-10-22 12:35 UTC, vlolad commented on src/converter/JsonTaskParser.java
> +public class JsonTaskParser {
Так как используется через метод в HttpTaskServer, лучше перенести создание Gson полностью туда и уже оттуда вызывать во все необходимые места (это обязательная правка).

Также можно каждый раз и новый инстанс Gson возвращать (если для каждого "вызова" создается отдельный инстанс парсера, это будет даже правильнее, но по желанию)
И рекомендую посмотреть GsonBuilder. Упрощает создание, когда надо вариативно добавлять адаптеры

2024-10-22 12:35 UTC, vlolad commented on src/converter/StatusTypeAdapter.java
> +public class StatusTypeAdapter extends TypeAdapter<Status> {
Я не успел протестировать, но кажется, это из коробки будет работать без создания адаптера

2024-10-22 12:35 UTC, vlolad commented on src/model/Subtask.java
> +        epic.addSubTask(this);
Главное, чтобы менеджер этот момент тоже учёл и пересчитал статус эпика

2024-10-22 12:35 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        return identifier;
В таком случае можно `return ++identifier;` 
Почитай, в чём отличие для разного расположения операторов

2024-10-22 12:35 UTC, vlolad commented on src/web/BaseHttpHandler.java
> +            return gson.fromJson(subtitlesJson, new EpicTypeToken().getType());
Можно проще, без TypeAdapter - `gson.fromJson(json, Epic.class);` и т.п.

2024-10-22 12:35 UTC, vlolad commented on src/web/BaseHttpHandler.java
> +        Gson gson = JsonTaskParser.gson;
Надо сделать Gson gson полем класса и получать из HttpTaskServer при создании

2024-10-22 12:35 UTC, vlolad commented on src/web/BaseHttpHandler.java
> +        }
Это ок, но API запросов не реализовано так, как это требуется в ТЗ. Нет отдельных эндпоинтов для разных типов задач и операций, всё в одной куче и поддерживать это тяжело

Методы обработки запросов для разных типов задач лучше вынести в разные классы (EpicsHandler, TasksHandler, PrioritizedHandler и т.д.), которые будут наследоваться от этого класса. Тут надо оставить базовый функционал по направлению текста/ошибок и т.д

2024-10-22 12:35 UTC, vlolad commented on src/web/HttpTaskServer.java
> +        httpServer.stop(2);
При завершении без ошибок ставят код завершения 0

2024-10-22 12:35 UTC, vlolad commented on src/web/HttpTaskServer.java
> +        httpServer.createContext("/subtasks", new BaseHttpHandler(taskManager));
Продублирую комментарий - это должны быть разные хендлеры для разных типов задач

2024-10-22 12:35 UTC, vlolad commented on src/web/BaseHttpHandler.java
> +                    } else if (arrayPath.length == 4 && arrayPath[1].equals("epics") && arrayPath[3].equals("subtasks")) {
Проще обрабатывать Path в данном случае, поскольку можно просто написать path.contains("subtasks"), например. Не придется вручную проверять массив и менять код, особенно если эндпоинт поменяется
Для этого вместо String[] arrayPath = httpExchange.getRequestURI().getPath().split("/"); можно просто Path path = httpExchange.getRequestURI().getPath();

2024-10-22 17:25 UTC, CMEL123 commented on src/web/BaseHttpHandler.java
> +                    } else if (arrayPath.length == 4 && arrayPath[1].equals("epics") && arrayPath[3].equals("subtasks")) {
Тут не очень согласен с вами, так как, мне кажется, важно проверять последовательность, поэтому оставлю как есть

2024-10-23 13:04 UTC, vlolad approved these changes
Привет!

Всё отлично, все правки доработаны.
NB для будущих проектов - код 406 редко используется в ответах, чаще всего - 400 (когда ошибка связана с запросом) или 401/403 (доступы). До сих пор не знаю, почему в ТЗ требуют код 406 возвращать в ряде случаев, где явно нужен 400, но окей

Поздравляю с завершением первого большого проекта!

2024-10-23 13:13 UTC, merged